apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: uber-clone
type: Opaque
data:
  mongo-username: dXNlcm5hbWU= # base64 encoded value of 'username'
  mongo-password: cGFzc3dvcmQ= # base64 encoded value of 'password'
